
// Unicode characters to clean with their descriptions and replacement rules
export const UNICODE_CHARS = {
  // White_Space = yes characters (25 characters)
  '\u0009': { name: 'Character Tabulation (HT)', replaceWith: '\t' },
  '\u000A': { name: 'Line Feed (LF)', replaceWith: '\n' },
  '\u000B': { name: 'Line Tabulation (VT)', replaceWith: ' ' },
  '\u000C': { name: 'Form Feed (FF)', replaceWith: ' ' },
  '\u000D': { name: 'Carriage Return (CR)', replaceWith: '\r' },
  '\u0020': { name: 'Space', replaceWith: ' ' },
  '\u0085': { name: 'Next Line (NEL)', replaceWith: '\n' },
  '\u00A0': { name: 'No-Break Space (NBSP)', replaceWith: ' ' },
  '\u1680': { name: 'Ogham Space Mark', replaceWith: ' ' },
  '\u2000': { name: 'En Quad', replaceWith: ' ' },
  '\u2001': { name: 'Em Quad', replaceWith: ' ' },
  '\u2002': { name: 'En Space', replaceWith: ' ' },
  '\u2003': { name: 'Em Space', replaceWith: ' ' },
  '\u2004': { name: 'Three-Per-Em Space', replaceWith: ' ' },
  '\u2005': { name: 'Four-Per-Em Space', replaceWith: ' ' },
  '\u2006': { name: 'Six-Per-Em Space', replaceWith: ' ' },
  '\u2007': { name: 'Figure Space', replaceWith: ' ' },
  '\u2008': { name: 'Punctuation Space', replaceWith: ' ' },
  '\u2009': { name: 'Thin Space', replaceWith: ' ' },
  '\u200A': { name: 'Hair Space', replaceWith: ' ' },
  '\u2028': { name: 'Line Separator', replaceWith: '\n' },
  '\u2029': { name: 'Paragraph Separator', replaceWith: '\n\n' },
  '\u202F': { name: 'Narrow No-Break Space (NNBSP)', replaceWith: ' ' },
  '\u205F': { name: 'Medium Mathematical Space (MMSP)', replaceWith: ' ' },
  '\u3000': { name: 'Ideographic Space', replaceWith: ' ' },
  
  // Additional invisible formatting characters (White_Space = no)
  '\u180E': { name: 'Mongolian Vowel Separator (MVS)', replaceWith: '' },
  '\u200B': { name: 'Zero Width Space (ZWSP)', replaceWith: '' },
  '\u200C': { name: 'Zero Width Non-Joiner (ZWNJ)', replaceWith: '' },
  '\u200D': { name: 'Zero Width Joiner (ZWJ)', replaceWith: '' },
  
  // Additional characters from the original list
  '\u034F': { name: 'Combining Grapheme Joiner', replaceWith: '' },
  '\u061C': { name: 'Arabic Letter Mark', replaceWith: '' },
  '\u200E': { name: 'Left-to-Right Mark', replaceWith: '' },
  '\u200F': { name: 'Right-to-Left Mark', replaceWith: '' },
  '\u202A': { name: 'Left-to-Right Embedding', replaceWith: '' },
  '\u202B': { name: 'Right-to-Left Embedding', replaceWith: '' },
  '\u202C': { name: 'Pop Directional Formatting', replaceWith: '' },
  '\u202D': { name: 'Left-to-Right Override', replaceWith: '' },
  '\u202E': { name: 'Right-to-Left Override', replaceWith: '' },
  '\u2060': { name: 'Word Joiner', replaceWith: '' },
  '\u2061': { name: 'Function Application', replaceWith: '' },
  '\u2062': { name: 'Invisible Times', replaceWith: '' },
  '\u2063': { name: 'Invisible Separator', replaceWith: '' },
  '\u2064': { name: 'Invisible Plus', replaceWith: '' },
  '\u2065': { name: 'Invisible Plus', replaceWith: '' },
  '\u2066': { name: 'Left-to-Right Isolate', replaceWith: '' },
  '\u2067': { name: 'Right-to-Left Isolate', replaceWith: '' },
  '\u2068': { name: 'First Strong Isolate', replaceWith: '' },
  '\u2069': { name: 'Pop Directional Isolate', replaceWith: '' },
  '\u206A': { name: 'Inhibit Symmetric Swapping', replaceWith: '' },
  '\u206B': { name: 'Activate Symmetric Swapping', replaceWith: '' },
  '\u206C': { name: 'Inhibit Arabic Form Shaping', replaceWith: '' },
  '\u206D': { name: 'Activate Arabic Form Shaping', replaceWith: '' },
  '\u206E': { name: 'National Digit Shapes', replaceWith: '' },
  '\u206F': { name: 'Nominal Digit Shapes', replaceWith: '' },
  '\u2800': { name: 'Braille Pattern Blank', replaceWith: ' ' },
  '\uFEFF': { name: 'Zero Width No-Break Space', replaceWith: '' },
  '\uFFA0': { name: 'Halfwidth Hangul Filler', replaceWith: '' },
  '\uFFFC': { name: 'Object Replacement Character', replaceWith: '' },
};
